default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_conf: &default_conf
  host: user_db
  username: root
  password: password

development:
  user:
    <<: *default
    <<: *default_conf
    database: rails_docker_app_user_development
    migrations_paths: db/user_migrate
  user_replica:
    <<: *default
    <<: *default_conf
    database: rails_docker_app_user_development
    replica: true

test:
  <<: *default
  <<: *default_conf
  database: rails_docker_app_test

production:
  <<: *default
  database: rails_docker_app_production
  username: rails_docker_app
  password: <%= ENV["RAILS_DOCKER_APP_DATABASE_PASSWORD"] %>
