default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: primary_db
  username: root
  password: password

development:
  primary:
    <<: *default
    database: rails_docker_app_primary_development
  primary_replica:
    <<: *default
    database: rails_docker_app_primary_development
    replica: true

test:
  <<: *default
  database: rails_docker_app_primary_test

production:
  <<: *default
  database: rails_docker_app_production
  username: rails_docker_app
  password: <%= ENV["RAILS_DOCKER_APP_DATABASE_PASSWORD"] %>
