default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_conf: &default_conf
  host: db
  username: root
  password: password

development:
  <<: *default
  <<: *default_conf
  database: rails_docker_app_development

test:
  <<: *default
  <<: *default_conf
  database: rails_docker_app_test

production:
  <<: *default
  database: rails_docker_app_production
  username: rails_docker_app
  password: <%= ENV["RAILS_DOCKER_APP_DATABASE_PASSWORD"] %>
